version: '3.8'

services:
  backend:
    build: .
    ports:
      - "5000:5000"              
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://as0846403:z7RSjHkLSUN9Wd9j@cluster0.6q7gapy.mongodb.net/
      - REDIS_URI=redis://redis:6379
      - JWT_SECRET=e3ff5f077839c1331b1d893a728246685cb7dba9e3a77bffe7d52eaccf660988
      - JWT_EXPIRES_IN=15m
      - REFRESH_TOKEN_EXPIRES_IN=7d
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  mongo-data:
